### ISSUE TITLE
Get Access to the CustomControl from a Lib in App.controller.ts

### ISSUE THREAD

**Issue by Kasde96** [petermuessig/typescript-app-and-lib-plus-npm-packages#1]
Hallo @petermuessig, 

I want to import my "Example" control into App.controller.ts. 
When I start the app, it works fine. Unfortunately, the linter in the file tells me that it does not have access to the module. 
Also the code completion does not work properly because the module is not recognized.
How do I manage to import the control into the controller? 

![image](https://github.com/petermuessig/typescript-app-and-lib-plus-npm-packages/assets/97966330/b8131bb4-2fe2-4101-bb2c-1c4a576fc0be).

Thanks,

Dominik

**Comment by petermuessig** [comment]
Hi @Kasde96 ,

the library needs to be built first - the `dist` folder with the types must exist. Sometimes after that it maybe necessary to restart the linter to find the new types - but in most cases it should be sufficient to build the library and then close and open the editor for the controller again.

HTH and BR,
Peter

**Comment by Kasde96** [comment]
Hi @petermuessig ,

sorry for the late response. Thank you for your guidance, it resolved my issue. 
Additionally, I encountered a problem where the _fiori add deploy-config_ command changes the ui5.yaml file. 
It is important that the customTask: _ui5-tooling-transpile-task_ is not modified. However, the command did make changes to it.

```yaml
builder:
  customTasks:
    - name: ui5-tooling-transpile-task
      afterTask: replaceVersion
      configuration:
        generateTsInterfaces: false # always generate the TS interfaces in build
```
I close the issue. 

Thanks,
Dominik
